package gui;
import repository.CRUD;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class KelolaUserFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaUserFrame.class.getName());

    /**
     * Creates new form KelolaUserFrame
     */
    public KelolaUserFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Manage Users");
        tampilData();
    }
    
    public void tampilData() {
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);

        CRUD crud = new CRUD();

        try {
            ResultSet rs = crud.tampilSemuaUser();

            while (rs.next()) {
                if ("user".equalsIgnoreCase(rs.getString("hak_akses"))) {
                    Object[] data = {
                        rs.getString("id_pengguna"),
                        rs.getString("nama_lengkap"),
                        rs.getString("username"),
                        rs.getString("email"),
                        rs.getString("hak_akses")
                    };
                    model.addRow(data);
                }
            }

        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }

    public void tampilDataCari(String kataKunci) {
        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();
        model.setRowCount(0);

        CRUD crud = new CRUD();

        try {
            ResultSet rs = crud.cariUser(kataKunci);

            while (rs.next()) {
                if ("user".equalsIgnoreCase(rs.getString("hak_akses"))) {
                    Object[] data = {
                        rs.getString("id_pengguna"),
                        rs.getString("nama_lengkap"),
                        rs.getString("username"),
                        rs.getString("email"),
                        rs.getString("hak_akses")
                    };
                    model.addRow(data);
                }
            }

        } catch (SQLException e) {
            System.out.println("Error cari : " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblCari = new javax.swing.JLabel();
        txtKataKunci = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        scrollUser = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCari.setText("Cari");

        txtKataKunci.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Pengguna", "Nama Lengkap", "Username", "Email", "Hak Akses"
            }
        ));
        scrollUser.setViewportView(tblUser);

        judul.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        judul.setText("KELOLA USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refresh.setText("Refresh");
        refresh.addActionListener(this::refreshActionPerformed);

        edit.setText("Edit");
        edit.addActionListener(this::editActionPerformed);

        hapus.setText("Hapus");
        hapus.addActionListener(this::hapusActionPerformed);

        kembali.setText("Kembali");
        kembali.addActionListener(this::kembaliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(refresh)
                .addGap(117, 117, 117)
                .addComponent(edit)
                .addGap(125, 125, 125)
                .addComponent(hapus)
                .addGap(108, 108, 108)
                .addComponent(kembali)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(238, 238, 238))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(scrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(txtKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(scrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh)
                    .addComponent(edit)
                    .addComponent(hapus)
                    .addComponent(kembali))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int baris = tblUser.getSelectedRow();

        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih user yang akan dihapus!");
            return;
        }

        int idPengguna = Integer.parseInt(
                tblUser.getValueAt(baris, 0).toString());

        int jawab = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus user ini?",
                "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (jawab == javax.swing.JOptionPane.YES_OPTION) {

            CRUD crud = new CRUD();

            if (crud.hapusUser(idPengguna)) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "User berhasil dihapus");

                tampilData();

            } else {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "User gagal dihapus");
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new HalamanAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tampilData();
    }//GEN-LAST:event_refreshActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int baris = tblUser.getSelectedRow();

        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Pilih user terlebih dahulu!");
            return;
        }

        int idPengguna = Integer.parseInt(
                tblUser.getValueAt(baris, 0).toString());

        String namaLengkap =
                tblUser.getValueAt(baris, 1).toString();

        String username =
                tblUser.getValueAt(baris, 2).toString();

        String email =
                tblUser.getValueAt(baris, 3).toString();

        String hakAkses =
                tblUser.getValueAt(baris, 4).toString();

        namaLengkap = javax.swing.JOptionPane.showInputDialog(
                this,
                "Nama Lengkap",
                namaLengkap);

        username = javax.swing.JOptionPane.showInputDialog(
                this,
                "Username",
                username);

        email = javax.swing.JOptionPane.showInputDialog(
                this,
                "Email",
                email);

        hakAkses = javax.swing.JOptionPane.showInputDialog(
                this,
                "Hak Akses",
                hakAkses);

        CRUD crud = new CRUD();

        boolean berhasil = crud.editUser(
                idPengguna,
                namaLengkap,
                username,
                email,
                hakAkses);

        if (berhasil) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Data berhasil diubah");

            tampilData();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Data gagal diubah");
        }
    }//GEN-LAST:event_editActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String kataKunci = txtKataKunci.getText();
        tampilDataCari (kataKunci);
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaUserFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel lblCari;
    private javax.swing.JButton refresh;
    private javax.swing.JScrollPane scrollUser;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtKataKunci;
    // End of variables declaration//GEN-END:variables
}
