package gui;
import repository.CRUD;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class KelolaJadwalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaJadwalFrame.class.getName());

    /**
     * Creates new form KelolaJadwalFrame
     */
    public KelolaJadwalFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Manage Schedules");
        tampilData();
    }

    public void tampilData() {
        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0);

        CRUD crud = new CRUD();
        crud.updateStatusOtomatis();

        try {
            ResultSet rs = crud.tampilSemuaKegiatanAdmin();

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_kegiatan"),
                    rs.getString("nama_kegiatan"),
                    rs.getString("kategori"),
                    rs.getString("tanggal"),
                    rs.getString("jam"),
                    rs.getString("prioritas"),
                    rs.getString("keterangan"),
                    rs.getString("status")
                };
                model.addRow(data);
            }

        } catch (SQLException e) {
            System.out.println("Error tampil data: " + e.getMessage());
        }
    }
    
    public void tampilDataCari(String kataKunci) {
        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0);

        CRUD crud = new CRUD();
        crud.updateStatusOtomatis();

        try {
            ResultSet rs = crud.cariKegiatanAdmin(kataKunci);

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_kegiatan"),
                    rs.getString("nama_kegiatan"),
                    rs.getString("kategori"),
                    rs.getString("tanggal"),
                    rs.getString("jam"),
                    rs.getString("prioritas"),
                    rs.getString("keterangan"),
                    rs.getString("status")
                };
                model.addRow(data);
            }

        } catch (SQLException e) {
            System.out.println("Error cari data: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        temukan = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(746, 415));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cari");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 100, 40, 20);
        jPanel1.add(temukan);
        temukan.setBounds(350, 100, 177, 22);

        enter.setText("Cari");
        enter.addActionListener(this::enterActionPerformed);
        jPanel1.add(enter);
        enter.setBounds(560, 100, 72, 23);

        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Kegiatan", "Nama Kegiatan", "Kategori", "Tanggal", "Jam", "Prioritas", "Keterangan", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblJadwal);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 180, 710, 135);

        refresh.setText("Refresh");
        refresh.addActionListener(this::refreshActionPerformed);
        jPanel1.add(refresh);
        refresh.setBounds(20, 340, 90, 23);

        edit.setText("Edit");
        edit.addActionListener(this::editActionPerformed);
        jPanel1.add(edit);
        edit.setBounds(210, 340, 80, 23);

        hapus.setText("Hapus");
        hapus.addActionListener(this::hapusActionPerformed);
        jPanel1.add(hapus);
        hapus.setBounds(400, 340, 80, 23);

        kembali.setText("Kembali");
        kembali.addActionListener(this::kembaliActionPerformed);
        jPanel1.add(kembali);
        kembali.setBounds(570, 340, 100, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2026-06-28 at 10.03.11.jpeg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String kataKunci = temukan.getText();
        tampilDataCari(kataKunci);
    }//GEN-LAST:event_enterActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int baris = tblJadwal.getSelectedRow();

        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih kegiatan yang akan dihapus!");
            return;
        }

        int idKegiatan = Integer.parseInt(
            tblJadwal.getValueAt(baris, 0).toString());

        int jawab =
            javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus kegiatan ini?",
                "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (jawab == javax.swing.JOptionPane.YES_OPTION) {
            CRUD crud = new CRUD();

            if (crud.hapusKegiatan(idKegiatan)) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Kegiatan berhasil dihapus");
                tampilData();
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Kegiatan gagal dihapus");
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int baris = tblJadwal.getSelectedRow();

        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih kegiatan terlebih dahulu!");
            return;
        }

        int idKegiatan = Integer.parseInt(
            tblJadwal.getValueAt(baris, 0).toString());

        String namaKegiatan =
            tblJadwal.getValueAt(baris, 1).toString();

        String kategori =
            tblJadwal.getValueAt(baris, 2).toString();

        String tanggal =
            tblJadwal.getValueAt(baris, 3).toString();

        String jam =
            tblJadwal.getValueAt(baris, 4).toString();

        String prioritas =
            tblJadwal.getValueAt(baris, 5).toString();

        String status =
            tblJadwal.getValueAt(baris, 6).toString();

        namaKegiatan = javax.swing.JOptionPane.showInputDialog(
            this,
            "Nama Kegiatan",
            namaKegiatan);

        kategori = javax.swing.JOptionPane.showInputDialog(
            this,
            "Kategori",
            kategori);

        tanggal = javax.swing.JOptionPane.showInputDialog(
            this,
            "Tanggal",
            tanggal);

        jam = javax.swing.JOptionPane.showInputDialog(
            this,
            "Jam",
            jam);

        prioritas = javax.swing.JOptionPane.showInputDialog(
            this,
            "Prioritas",
            prioritas);

        status = javax.swing.JOptionPane.showInputDialog(
            this,
            "Status",
            status);
        
        CRUD crud = new CRUD();

        boolean berhasil = crud.editKegiatan(
            idKegiatan,
            namaKegiatan,
            kategori,
            tanggal,
            jam,
            prioritas,
            status);

        if (berhasil) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Data kegiatan berhasil diubah");
            tampilData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Data kegiatan gagal diubah");
        }
    }//GEN-LAST:event_editActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new HalamanAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        tampilData();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaJadwalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JButton enter;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tblJadwal;
    private javax.swing.JTextField temukan;
    // End of variables declaration//GEN-END:variables
}
