package gui;
import entity.*;
import repository.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dwi Sekar
 */
public class LihatJadwalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LihatJadwalFrame.class.getName());
    CRUD crud = new CRUD();
    private int idPengguna;
    
    /**
     * Creates new form LihatJadwalFrame
     */
    public LihatJadwalFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("View Schedule");
    }
    
    public LihatJadwalFrame(int idPengguna) {
        this();
        this.idPengguna = idPengguna;
        tampilkanJadwal();
    }
    
    private void tampilkanJadwal() {
        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = crud.tampilSemuaKegiatan(idPengguna);
            SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatJam = new SimpleDateFormat("HH:mm");
            Date sekarang = new Date();

            while (rs.next()) {
                String status = rs.getString("status");
                Date tgl = formatTgl.parse(rs.getString("tanggal"));
                Date jam = formatJam.parse(rs.getString("jam"));

                Calendar waktu = Calendar.getInstance();
                waktu.setTime(tgl);
                Calendar jamKal = Calendar.getInstance();
                jamKal.setTime(jam);
                waktu.set(Calendar.HOUR_OF_DAY, jamKal.get(Calendar.HOUR_OF_DAY));
                waktu.set(Calendar.MINUTE, jamKal.get(Calendar.MINUTE));
                waktu.set(Calendar.SECOND, 0);

                boolean sudahLewat = waktu.getTimeInMillis() < sekarang.getTime();

                if (status.equalsIgnoreCase("Belum Selesai") && !sudahLewat) {
                    model.addRow(new Object[]{
                        rs.getInt("id_kegiatan"),
                        rs.getString("nama_kegiatan"),
                        rs.getString("kategori"),
                        rs.getString("tanggal"),
                        rs.getString("jam"),
                        rs.getString("prioritas"),
                        status,
                        rs.getString("keterangan")
                    });
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat jadwal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        scrollJadwal = new javax.swing.JScrollPane();
        tblJadwal = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(726, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("My Routine Schedule");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 20, 196, 26);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(520, 30, 65, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(220, 30, 65, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(210, 50, 400, 10);

        lblCari.setText("Cari :");
        jPanel1.add(lblCari);
        lblCari.setBounds(290, 80, 40, 20);

        txtCari.addActionListener(this::txtCariActionPerformed);
        jPanel1.add(txtCari);
        txtCari.setBounds(350, 80, 250, 22);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);
        jPanel1.add(btnCari);
        btnCari.setBounds(610, 80, 72, 23);

        tblJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Kegiatan", "Kategori", "Tanggal", "Jam", "Prioritas", "Status", "Keterangan"
            }
        ));
        scrollJadwal.setViewportView(tblJadwal);

        jPanel1.add(scrollJadwal);
        scrollJadwal.setBounds(6, 137, 704, 170);

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel1.add(btnTambah);
        btnTambah.setBounds(21, 339, 74, 23);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel1.add(btnEdit);
        btnEdit.setBounds(113, 339, 70, 23);

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel1.add(btnHapus);
        btnHapus.setBounds(203, 339, 90, 23);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        jPanel1.add(btnKembali);
        btnKembali.setBounds(600, 339, 90, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2026-06-28 at 10.23.54.jpeg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, -4, 730, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 716, 384);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        btnCariActionPerformed(evt);
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
     int barisTerpilih = tblJadwal.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus terlebih dahulu!");
            return;
        }

        int idKegiatan = Integer.parseInt(tblJadwal.getValueAt(barisTerpilih, 0).toString());
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus jadwal ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean berhasil = crud.hapusKegiatan(idKegiatan);
            if (berhasil) {
                JOptionPane.showMessageDialog(null, "Jadwal berhasil dihapus!");
                tampilkanJadwal();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menghapus jadwal!");
            }
        }                                   
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
        CRUD crud = new CRUD();
        Pengguna pengguna = crud.ambilDataPengguna(idPengguna);
        new HalamanUtama(pengguna).setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        setVisible(false);
        TambahJadwalFrame tambah = new TambahJadwalFrame(idPengguna);
        tambah.setLocationRelativeTo(null);
        
        tambah.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setVisible(true);
                tampilkanJadwal();
            }
        });
        tambah.setVisible(true);                                  
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int barisTerpilih = tblJadwal.getSelectedRow();
        if (barisTerpilih == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah terlebih dahulu!");
            return;
        }

        int idKegiatan = Integer.parseInt(tblJadwal.getValueAt(barisTerpilih, 0).toString());
        setVisible(false);
        TambahJadwalFrame ubah = new TambahJadwalFrame(idPengguna, idKegiatan);
        ubah.setLocationRelativeTo(null);
        ubah.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setVisible(true);
                tampilkanJadwal();
            }
        });
        ubah.setVisible(true);                       
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String kataKunci = txtCari.getText().trim();
        DefaultTableModel model = (DefaultTableModel) tblJadwal.getModel();
        model.setRowCount(0);
        
        if (kataKunci.isEmpty()) {
            tampilkanJadwal();
            return;
        }

        ResultSet rs = crud.cariKegiatan(idPengguna, kataKunci);
        List<Kegiatan> hasilCari = new ArrayList<>();

        try {
            while (rs.next()) {
                Kegiatan k = new Kegiatan(
                    rs.getInt("id_kegiatan"),
                    rs.getInt("id_pengguna"),
                    rs.getString("nama_kegiatan"),
                    rs.getString("kategori"),
                    rs.getString("tanggal"),
                    rs.getString("jam"),
                    rs.getString("prioritas"),
                    rs.getString("keterangan"),
                    rs.getString("status")
                );
                hasilCari.add(k);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal melakukan pencarian: " + e.getMessage());
            return;
        }

        for (Kegiatan k : hasilCari) {
            model.addRow(new Object[]{
                k.getIdKegiatan(),
                k.getNamaKegiatan(),
                k.getKategori(),
                k.getTanggal(),
                k.getJam(),
                k.getPrioritas(),
                k.getStatus(),
                k.getKeterangan()
            });
        }                                     
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LihatJadwalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCari;
    private javax.swing.JScrollPane scrollJadwal;
    private javax.swing.JTable tblJadwal;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
