package gui;
import entity.*;
import entity.User;
import repository.CRUD;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class RegisterFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterFrame.class.getName());

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Register");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        konfir = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(690, 390));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(1, 1, 107));
        jPanel1.setForeground(new java.awt.Color(1, 1, 107));
        jPanel1.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PENGELOLAAN");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 120, 130, 25);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("JADWAL KEGIATAN");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 150, 171, 35);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kelola jadwal kegiatan Anda");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 220, 162, 16);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("dengan mudah dan terorganisir");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 240, 177, 20);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(6, 200, 197, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 190, 400);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Create Account");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 30, 160, 27);

        jLabel2.setText("Silakan lengkapi data diri untuk membuat akun baru");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 70, 290, 16);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 100, 92, 20);

        nama.setOpaque(true);
        nama.addActionListener(this::namaActionPerformed);
        jPanel2.add(nama);
        nama.setBounds(154, 120, 160, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 100, 62, 20);

        uname.addActionListener(this::unameActionPerformed);
        jPanel2.add(uname);
        uname.setBounds(336, 120, 160, 22);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(160, 160, 32, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 160, 58, 20);
        jPanel2.add(email);
        email.setBounds(154, 180, 160, 22);
        jPanel2.add(pw);
        pw.setBounds(336, 180, 160, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Konfirmasi Password");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(160, 220, 126, 20);
        jPanel2.add(konfir);
        konfir.setBounds(150, 240, 340, 22);

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setText("Register");
        register.setOpaque(true);
        register.addActionListener(this::registerActionPerformed);
        jPanel2.add(register);
        register.setBounds(151, 290, 350, 23);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(148, 330, 130, 10);

        jLabel8.setText("atau");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(290, 320, 40, 16);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(340, 330, 160, 10);

        jLabel9.setText("Sudah punya akun?");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 350, 120, 16);

        login.setForeground(new java.awt.Color(34, 76, 203));
        login.setText("Login disini");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jPanel2.add(login);
        login.setBounds(350, 350, 80, 16);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/WhatsApp Image 2026-06-26 at 10.34.28.jpeg"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(-140, 0, 660, 390);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 0, 530, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String namaLengkap = nama.getText();
        String username = uname.getText();
        String emailUser = email.getText();
        String password = String.valueOf(pw.getPassword());
        String konfirmasi = String.valueOf(konfir.getPassword());

        if (!password.equals(konfirmasi)) {
            JOptionPane.showMessageDialog(this, "Konfirmasi password tidak sesuai!");
            return;
        }

        User user = new User(
            0,
            namaLengkap,
            username,
            emailUser,
            password,
            "user"
        );

        CRUD crud = new CRUD();

        if (crud.registerUser(user)) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil!");
            new LoginFrame().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal!");
        }
    }//GEN-LAST:event_registerActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_loginMouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField konfir;
    private javax.swing.JLabel login;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField pw;
    private javax.swing.JButton register;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
